### ISSUE TITLE
Confusion around remote_signer_config.json

### ISSUE THREAD

**Issue by koraykoska** [stakewise/v3-operator#299]
We manually created keystore files and imported them to web3signer (not using the stakewise operator).

Now it turns out that a `remote_signer_config.json` is required, which would have been generated as a result of using the setup step for web3signer.

[The Guide](https://docs.stakewise.io/for-operators/operator-service/running-with-remote-signer) was not clear about the setup step being a requirement ("If you already have private keys uploaded to the remote signer, proceed to running the operator.")

1) What is this file? I saw that private keys are split and the shares are saved in this file. Why?
2) Is it possible to not use this structure?
3) If not possible differently, how can I generate this json file without doing the setup step? It's difficult with our infrastructure and I would like to avoid it.

**Comment by evgeny-stakewise** [comment]
Updated remote signer flow was included in public release (since [v1.1.0](https://github.com/stakewise/v3-operator/releases/tag/v1.1.0)). So the issue can be closed now.
